apiVersion: apps/v1
kind: Deployment
metadata:
  name: sap
  labels:
    app: sap
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sap-konrad-graphql
  template:
    metadata:
      labels:
        app: sap
    spec:
      containers:
      - name: sap-react
        image: konrazem/sap-react:1
        ports:
        - containerPort: 80
      - name: sap-graphql
        image: konrazem/sap-graphql:mongodocker
        ports:
        - containerPort: 3001
